[package]
name = "k64"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "k64"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
limine = "0.3.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
